BARRIER = r'##############################################################'
ERROR = r'ERRORERRORERRORERRORERRORERRORERRORERRORERRO' \
         'RERRORERRORERRORERRORERRORERRORERRORERRORERR' \
         'ORERRORERRORERRORERRORERROR'
